# Generated by Django 4.1.3 on 2023-03-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
